version: "3.8"
services:
  api-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: <Strong!Passw0rd>
    volumes:
      - api-database:/var/opt/mssql
  identity-provider:
    build:
      context: ../
      dockerfile: ./blazor-keycloak/identity-provider/Dockerfile
    image: blazor-keycloak-web-idp:dev
    ports:
      - "8080:8080"
